# Generated by Django 5.2.7 on 2025-10-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='move_type',
            field=models.CharField(choices=[('Regular', 'Regular Move'), ('Long', 'Long Move'), ('Pallete', 'Pallete Return')], default='regular', max_length=25),
        ),
    ]
