# Generated by Django 5.2.7 on 2025-10-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_shift_move_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='move_type',
            field=models.CharField(choices=[('regular', 'Regular Move'), ('long', 'Long Move'), ('pallete', 'Pallete Return')], default='regular', max_length=25),
        ),
    ]
