# Generated by Django 5.2.7 on 2025-10-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_downtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downtime',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='downtime',
            name='start_time',
        ),
        migrations.AddField(
            model_name='downtime',
            name='duration',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
