# Generated by Django 5.2.7 on 2025-10-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_downtime_end_time_remove_downtime_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='duration',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
